# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Security\Firewall\Authentication\SteamProvider:
        arguments: ['@security.user.provider.concrete.users_in_memory','@.debug.http_client']

    #app.steam_auth_event_listener:    
        #class: App\Security\Firewall\SteamAuthListener
        #tags:
            #- { name: 'kernel.event_listener', event: 'kernel.response', method: 'onKernelResponse' }
        #arguments: ['home','@security.token_storage', '@security.authentication.manager','@security.authentication.manager']
        
    App\Security\Firewall\SteamAuthListener:
        arguments: ['home','@security.token_storage', '@security.authentication.manager','@router.default']
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    #Token